name: Premake compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # a reference to an old OSFirstTimer video
  build-abunchew:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Run premake '5.0.0-beta1'
      uses: eariassoto/setup-premake@v1
      with:
        version: '5.0.0-beta1'
        action: 'gmake'
        options: '--cc=clang'

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Run premake '5.0.0-beta1'
      uses: eariassoto/setup-premake@v1
      with:
        version: '5.0.0-beta1'
        action: 'gmake2'
