name: Compile

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Run premake
      uses: abel0b/setup-premake@v2.3
      with:
        version: '5.0.0-beta2'

    - name: Compile my project
      run: |
          premake5 gmake2
          make
